site_name: SkillCheck Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Technical Document:
      - Functional Specification: requirements/functional-document.md
      - Use Case Document: requirements/use-case-document.md
      - Entity Relationship Diagram: requirements/erd.md
      - System Architecture: requirements/system-architecture.md
      - Data Flow: requirements/dfd.md
      - Authentication and Authorization: requirements/sequence-auth2.md
      - Test Plan: requirements/test-plan.md
      

plugins:
  - mermaid2