site_name: SkillCheck Documentation

theme:
  name: material
  
nav:
  - Home: index.md
  - Requirements:
      - Functional Specification: requirements/functional-document.md
      - Use Case Document: requirements/use-case-document.md
      

plugins:
  - mermaid2